name: build

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  server-ci-and-release:
    uses: ./.github/workflows/ci-reusable-workflow.yml
    with:
      working-directory: ./server
      go-version: 1.18
  cli-ci-and-release:
    uses: ./.github/workflows/ci-reusable-workflow.yml
    with:
      working-directory: ./cli
      go-version: 1.17