name: Create and Publish Petra docker image to ghcr.io

on:
  push: 
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: petra
  WORKING_DIRECTORY: ./server

jobs:
  publish-petra-server:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Google Auth
        id: google-auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.SA_GCP_ARTIFACT_REGISTRY}}'

      - name: Artifact Registry Auth
        id: artifact-registry-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.google-auth.outputs.access_token }}'
          registry: 'europe-west1-docker.pkg.dev'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release with goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          workdir: ${{env.WORKING_DIRECTORY}}
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
