name: Create and Publish Petra docker image to ghcr.io

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  publish-petra-server:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.working-directory}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Go
        uses: actions/setup-go@v3

      # - name: Make release
      #   run: make release
      - name: Create release with goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          workdir: ${{inputs.working-directory}}
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# name: Create and publish Petra server docker image to ghcr

# on:
#   workflow_call:
#     inputs:
#       working-directory:
#         required: true
#         type: string
#       go-version:
#         required: true
#         type: string

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: petra

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ${{inputs.working-directory}}
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Log in to the Container registry
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

# #      - name: Extract metadata (tags, labels) for Docker
# #        id: meta
# #        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
# #        with:
# #          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#         with:
#           context: ${{inputs.working-directory}}
#           push: true
#           tags: ghcr.io/devoteamgcloud/petra:latest
#           labels: ${{ steps.meta.outputs.labels }}